# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryrule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='countryrule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='countrytyperule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='countrytyperule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='defaultrule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='defaultrule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='destinationrule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='destinationrule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prefixrule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prefixrule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regionrule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regionrule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regiontyperule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regiontyperule',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
