# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 17:18
from __future__ import unicode_literals

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('customerdirectory', '0018_auto_20180406_1732'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerdirectory',
            index=partial_index.PartialIndex(fields=[b'name', b'callerid_norm'], name=b'customer_di_name_4ee2f6_partial', unique=True, where=b'', where_postgresql=b'enabled = True', where_sqlite=b''),
        ),
        migrations.AddIndex(
            model_name='customerdirectory',
            index=partial_index.PartialIndex(fields=[b'name', b'callee_norm'], name=b'customer_di_name_4c8c9c_partial', unique=True, where=b'', where_postgresql=b'enabled = True', where_sqlite=b''),
        ),
        migrations.AddIndex(
            model_name='customerdirectory',
            index=partial_index.PartialIndex(fields=[b'name', b'callerid_norm_in'], name=b'customer_di_name_a79ed4_partial', unique=True, where=b'', where_postgresql=b'enabled = True', where_sqlite=b''),
        ),
        migrations.AddIndex(
            model_name='customerdirectory',
            index=partial_index.PartialIndex(fields=[b'name', b'callee_norm_in'], name=b'customer_di_name_cbeaee_partial', unique=True, where=b'', where_postgresql=b'enabled = True', where_sqlite=b''),
        ),
    ]
