# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 17:14
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_auto_20180418_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'prefix'),
        ),
    ]
