# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0003_auto_20180427_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country_iso2',
        ),
    ]
