# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0004_remove_destination_country_iso2'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country_iso2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.Country', to_field=b'country_iso2', verbose_name='country'),
        ),
    ]
