# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callernumlist',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
