# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20180501_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerratecard',
            name='provider_prefix',
            field=models.CharField(blank=True, default=b'', max_length=10, verbose_name='prefix'),
        ),
    ]
